FROM node:22-alpine

WORKDIR /app

# ✅ First copy dependencies for caching
COPY package.json package-lock.json ./
RUN npm ci

# ✅ Copy app code after installing dependencies
COPY . .

EXPOSE 2000

ENTRYPOINT ["npm", "run"]
CMD ["start"]